### PR TITLE
[input wanted] Browser support linting

### PR DESCRIPTION
**Pull request by marekdedic**
Hey,
I've added browser support checking to the lint, both for js as well as css (well, not for css added by js...)

What I think should be debated is for which browsers this should check - that is controlled by the `browserlist` field in `package.json` - I've put something there to test it, but that is just a placeholder.

### CODE REVIEW

**Comment by rejas** [comment]
Could this replace the gulp-lintspaces too?

**Comment by GenaBitu** [comment]
AFAIK, lintspaces just checks things like whitespace, encoding, newlines and such... I think maybe eslint+stylelint could replace it with the right configuration.

But It could definitely replace csslint - csslint is actually supposed to be merged into stylelint at some point. I can add some more rules to stylelint and ditch csslint.

**Comment by paxperscientiam** [comment]
@GenaBitu this is a great idea as it'll allow for policy to be implicitly communicated to all would-be contributors and, of course, facilitate enforcement.

Testing it out now and very cool addition; the output of `gulp styelint` is informative. 

Can warnings for unsupported features be filtered out if the code explicitly tests for it?

Thinking of ie8, is possible to whitelist warnings per browser? 

Can the output be given in tabular form?

OK, no more questions :)

**Comment by GenaBitu** [comment]
Thanks.

You can supress warning of a particular line by putting `/* stylelint-disable-line plugin/no-unsupported-browser-features */` there. (You can also do larger blocks, but I haven't done that). There is also similar annotation for eslint (which currently produces no warnings, you can try it by putting something like `new Promise()`).

You can whitelist browsers - the full list of options is in [browserslist](https://github.com/browserslist/browserslist). I like the coverage options more because they will always be up-to-date with current usage, but it is possible to specify exactly the targeted browsers. Bear in mind that the list is a list of **target** browsers, so to disregard ie8 you would need to do something like `not ie8`

By tabular form you mean just a fancy CLI table or something like a JSON list? Both of the support plugins are basically just nice wrappers around a tool, which produces JSON (not 100% sure...)

**Comment by paxperscientiam** [comment]
"By tabular form you mean just a fancy CLI table ..."

Yeah, just for readability's sake.

**Comment by GenaBitu** [comment]
Hi,
you can format the output, yes. For ESLint, there are some formatters: (https://github.com/eslint/eslint/tree/master/lib/formatters), for stylelint, there are some as well, but no tabular one. Of course, you can [write your own](https://github.com/eslint/eslint/tree/master/lib/formatters)...

So, what about the support string? What should and should not be supported?

Adding "not ie 8" and "not OperaMini all" fixes *most* of the current failures. Disregarding Opera Mini is to me fine, ie 8 probably too. There are some things which complain about ie 9, but maybe they can be prefixed (it can't check that unfortunately). What are your opinions?

**Pull request merged**
