### PR TITLE
Magnify

### PR DESCRIPTION
**Pull request by paxperscientiam**
Hey @rejas . This is just a rough cut of what we talked about in issue #162 

So, don't interpret as final, but do give me your thoughts :D

### CODE REVIEW

**Comment by GenaBitu** [comment]
Hey, if I may, here's my 2 cents:
- you've accidentally commited `yarn.lock`
- magnify doesn't describe the intended functionality that clearly for me - maybe something like `fixedSize` or `sizeOverride`?
- the implementation looks fine, but I haven't tried it
- Honestly, the biggest issue for me is that I don't see the use case for this. I've seen your comments in #162 but if you could elaborate, maybe I would...

**Comment by paxperscientiam** [comment]
@GenaBitu To answer the most important question (use-case), it's utility would, in my mind, pertain to prototyping. 

Imagine being able to create galleries without nuisance of linking to external placeholder sites, or maintaining a set of placeholder images, or something like that. Just use a 1px data-uri and scale according to project needs.

Does that help?

**Comment by GenaBitu** [comment]
Umm, you probably have different needs from me (I have probably never needed to prototype in that way)... But that's fine, go ahead!

**Comment by paxperscientiam** [comment]
After playing around for a while, I have some questions.

First, let me note that split up the concepts of "placeholders" and "magnification". -- this PR is about magnification.

I was originally thinking of magnification as a developer option, but what if it were a userland option? 

This would boil down to three possibilities: no magnification, "static" magnification, and "interactive" magnification.

**Comment by marekdedic** [comment]
Hi @paxperscientiam, sorry to basically break this completely with #866 :( But I think it is worth it, it makes the code much more maintainable...

I want to refactor the `ImageView` some more still and I think this PR is unfortunately beyond saving... I am going to close it and we can look at fixing #162 in a new way. Let me know if you think this PR is worth rebasing. Thanks for understanding.

**Pull request closed without merging**
